stages:
  - build

build:
  stage: build
  script:
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install sphinx
    - pip install sphinxcontrib.youtube
    - make html
  tags:
    - openroad
    - flow
    - docs
  environment:
    name: docs
    url: https://docs.theopenroadproject.org