stages:
  - docs-build-publish

build:
  stage: docs-build-publish
  script:
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install sphinx
    - pip install sphinxcontrib.youtube
    - make html
    - cp -r build/* /var/www/html/docs
  environment:
    name: docs
    url: https://docs.theopenroadproject.org
